export default [
  {
    // totalTime: [1, 0, 3],
    sectionTime: [1, 0, 1],
    sectionTitle: "Section 1",
    sectionMark: [4, 0.5],
    components: [
      {
        componentTime: [0, 0, 5],
        componentTitle: "Comp 1",
        questions: [
          {
            question: {
              equ: "sdfa adfasdfasd sdffa sdfa dfasd afd fa d   fasdfasdfa sdfsd sdfsdfs fdfsdf erk ",
              img: "sssssssssss",
            },
            options: [
              { equ: "option 1" },
              { equ: "option 2", img: "ssss" },
              { equ: "option 3" },
              { img: "ssss" },
            ],
          },
          { question: "Question 2", options: ["1", "2", "3", "4"] },
          { question: "Question 3", options: ["1", "2", "3", "4"] },
          { question: "Question 4", options: ["1", "2", "3", "4"] },
          { question: "Question 5", options: ["1", "2", "3", "4"] },
          { question: "Question 6", options: ["1", "2", "3", "4"] },
          { question: "Question 2", options: ["1", "2", "3", "4"] },
          { question: "Question 3", options: ["1", "2", "3", "4"] },
          { question: "Question 4", options: ["1", "2", "3", "4"] },
          { question: "Question 5", options: ["1", "2", "3", "4"] },
          { question: "Question 6", options: ["1", "2", "3", "4"] },
          { question: "Question 2", options: ["1", "2", "3", "4"] },
          { question: "Question 3", options: ["1", "2", "3", "4"] },
          { question: "Question 4", options: ["1", "2", "3", "4"] },
          { question: "Question 5", options: ["1", "2", "3", "4"] },
          { question: "Question 6", options: ["1", "2", "3", "4"] },
          { question: "Question 2", options: ["1", "2", "3", "4"] },
          { question: "Question 3", options: ["1", "2", "3", "4"] },
          { question: "Question 4", options: ["1", "2", "3", "4"] },
          { question: "Question 5", options: ["1", "2", "3", "4"] },
          { question: "Question 6", options: ["1", "2", "3", "4"] },
          { question: "Question 2", options: ["1", "2", "3", "4"] },
          { question: "Question 3", options: ["1", "2", "3", "4"] },
          { question: "Question 4", options: ["1", "2", "3", "4"] },
          { question: "Question 5", options: ["1", "2", "3", "4"] },
          { question: "Question 6", options: ["1", "2", "3", "4"] },
        ],
      },
      {
        componentTime: [0, 0, 5],
        componentTitle: "Comp 2",
        directions: ["asdfsdsdf", "directions 2"],
        questions: [
          {
            direction: 0,
            question: "Question 11",
            options: ["1", "2", "3", "4"],
          },
          {
            direction: 1,
            question: "Question 22",
            options: ["1", "2", "3", "4"],
          },
          { question: "Question 33", options: ["1", "2", "3", "4"] },
          { question: "Question 44", options: ["1", "2", "3", "4"] },
          { question: "Question 55", options: ["1", "2", "3", "4"] },
          { question: "Question 66", options: ["1", "2", "3", "4"] },
          { question: "Question 11", options: ["1", "2", "3", "4"] },
          { question: "Question 22", options: ["1", "2", "3", "4"] },
          { question: "Question 33", options: ["1", "2", "3", "4"] },
          { question: "Question 44", options: ["1", "2", "3", "4"] },
          { question: "Question 55", options: ["1", "2", "3", "4"] },
          { question: "Question 66", options: ["1", "2", "3", "4"] },
        ],
      },
    ],
  },
  {
    sectionTime: [0, 0, 1],
    sectionTitle: "Section 2",
    components: [
      {
        componentTime: [0, 0, 20],
        componentTitle: "Comp 1",
        questions: [
          {
            question: "Question 1",
            options: ["1", "2", "3", "4"],
            mark: [3, 1],
          },
          {
            question: "Question 2",
            options: ["1", "2", "3", "4"],
            mark: [4, 1],
          },
          {
            question: "Question 3",
            options: ["1", "2", "3", "4"],
            mark: [5, 1],
          },
          {
            question: "Question 4",
            options: ["1", "2", "3", "4"],
            mark: [1, 1],
          },
          {
            question: "Question 5",
            options: ["1", "2", "3", "4"],
            mark: [1, 0],
          },
        ],
      },
    ],
  },
];
